name: cron

on:
  #push:
  schedule:
    - cron: '0 */3 * * *' #UTC - every 3 hours

jobs:
  cron:
    name: cron
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 8.4
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-dev -q

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Command
        run: php artisan ads:report
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          MAIL_MAILER: 'ses'
          MAIL_FROM_ADDRESS: ${{ secrets.MAIL_FROM_ADDRESS }}
          MAIL_FROM_NAME: ${{ secrets.MAIL_FROM_NAME }}
          MAIL_TO_ADDRESS: ${{ secrets.MAIL_TO_ADDRESS }}
          MAIL_TO_NAME: ${{ secrets.MAIL_TO_NAME }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT: ${{ secrets.GOOGLE_REDIRECT }}
          ADS_ACCESS_TOKEN: ${{ secrets.ADS_ACCESS_TOKEN }}
          ADS_REFRESH_TOKEN: ${{ secrets.ADS_REFRESH_TOKEN }}
          APP_LOCALE: ${{ secrets.APP_LOCALE }}
